from dataclasses import dataclass

from device.operations import ClientDeleteOperation, ClientInsertOperation
from unique_char.uniquechar import UniqueChar

# Insert operations that live in a state difference are synthesised by BuildSD rather than
# generated by a site, so they have no site id and no timestamp. Section 7.5 of Li and Li
# (2008) says only the deletions in a state difference need to carry one, because an
# exclusion transformation against an insertion is decided by position alone.
SYNTHETIC_CLIENT_ID = -1


@dataclass
class SDTInsertOperation:
    client_id: int
    vector_clock: dict[int, int]
    position: int
    # A single character for a real operation. BuildSD combines the characters that share a
    # beta value into one stringwise insert, so state difference entries can be longer.
    characters: list[UniqueChar]

    @property
    def length(self) -> int:
        return len(self.characters)


@dataclass
class SDTDeleteOperation:
    client_id: int
    vector_clock: dict[int, int]
    position: int
    character: UniqueChar

    @property
    def length(self) -> int:
        # Deletions are never combined by BuildSD, so they stay characterwise throughout.
        return 1


@dataclass
class SDTIdentityOperation:
    client_id: int
    vector_clock: dict[int, int]
    position: int

    @property
    def length(self) -> int:
        # No effect on the document, so no transformation ever shifts anything by it.
        return 0


SDTOperation = SDTInsertOperation | SDTDeleteOperation | SDTIdentityOperation


@dataclass
class SDTMessage:
    client_id: int
    vector_clock: dict[int, int]
    operation: SDTOperation
    causing_operation: ClientInsertOperation | ClientDeleteOperation
